version: 2
jobs:
  lint-package-index:
    docker:
      - image: helmpack/chart-releaser
    steps:
      - checkout
      - run:
          name: lint
          command: shellcheck -x .circleci/*.sh
      - run:
          name: package
          command: cr package ./speedtest-tracker
      - run:
          name: upload
          command: cr upload -o soblivionscall -r charts
      - run:
          name: index
          command: cr index -i ./index.yaml -p .deploy --owner soblivionscall --repo charts
  # release-charts:
  #   machine: true
  #   steps:
  #     - checkout
  #     - run:
  #         command: |
  #           echo "export GIT_REPOSITORY_URL=$CIRCLE_REPOSITORY_URL" >> $BASH_ENV
  #           echo "export GIT_USERNAME=$CIRCLE_PROJECT_USERNAME" >> $BASH_ENV
  #           echo "export GIT_REPOSITORY_NAME=$CIRCLE_PROJECT_REPONAME" >> $BASH_ENV
  #           .circleci/install_tools.sh
  #           .circleci/release.sh

workflows:
  version: 2
  release:
    jobs:
      - lint-package-index
      # - release-charts:
      #     filters:
      #       tags:
      #         ignore: /.*/
      #       branches:
      #         only: main