version: 2
jobs:
  package-upload-index:
    docker:
      - image: quay.io/helmpack/chart-releaser:v1.2.0 
    steps:
      - checkout
      - run:
          name: package
          command: |
            charts=$(find . -maxdepth 1 -type d \( ! -name .git ! -name .deploy ! -name .circleci ! -name . \) -print)
            for chart in $charts
            do
              cr package $chart
            done
      - run:
          name: upload
          command: cr upload -o soblivionscall -r charts
      - run:
          name: index
          command: |
            apk add git
            cr index -i ./index.yaml -o soblivionscall -c https://soblivionscall.github.io/charts/ -r charts --push

workflows:
  version: 2
  release:
    jobs:
      - package-upload-index:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: main